name: Push to main

on:
  push:
    branches:
      - apache-buster

env:
  PHP_VERSION: 8.1.20
  COMPOSER_VERSION: 2.6.5
  DEBIAN_VERSION: buster

jobs:
  Build-Push-Docker-Hub:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU to provide multiple architectures
        uses: docker/setup-qemu-action@v2

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx to build for multiple architectures
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-architecture images
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}
            PHP_VERSION=${{ env.PHP_VERSION }}
            COMPOSER_VERSION=${{ env.COMPOSER_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: voquis/cakephp:${{ env.PHP_VERSION }}-apache-buster
